refs = ["origin/main"]
ignore = ["./.claude/skills/skill-creator/**/*"]

[[tool]]
name = "cargo clippy"
configs = ["Cargo.toml"]

[[tool]]
name = "cargo fmt"
configs = ["Cargo.toml"]

[[tool]]
name = "mdlynx"

[[tool]]
name = "ruff check"
configs = []

[[tool]]
name = "ruff format"
configs = []

[[tool]]
name = "shellcheck"
configs = []

[[tool]]
name = "tagref"

[[tool]]
name = "ttlint"

[[tool]]
name = "ty"
configs = []

[[tool]]
name = "typos"
configs = []

[[tool]]
name = "zizmor"
configs = []
