# Usage:
#
#     - uses: langston-barrett/lun/.github/actions/lun@SHA
#

name: lun
description: Install and run lun
inputs:
  version:
    description: version (without the leading 'v')
    required: false
    default: '0.3.0'
  target:
    description: Target triple
    required: false
    default: 'x86_64-unknown-linux-gnu'
  flags:
    description: Flags to pass to `lun`
    required: false
    default: "-v"
  run-flags:
    description: Flags to pass to `lun run`
    required: false
    default: "--check"
runs:
  using: composite
  steps:
  - uses: langston-barrett/lun/.github/actions/install-lun@a802db7ff8a5680419d8e62d309b4ee698d06577
    with:
      version: ${{ inputs.version }}
      target: ${{ inputs.target }}
  - name: lun run
    shell: bash
    run: | # zizmor: ignore[template-injection]
      lun ${{ inputs.flags }} run ${{ inputs.run-flags }}
