name: rust ci
on:
  push:
    branches:
    - main
  pull_request:
    # Don't run on documentation-only changes
    paths-ignore: ["**.md"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@2038f7523e4ab93e52eb420a64e95f3b50edbe0a
    with:
      bench: false
      os: ubuntu-24.04
      # Run with just the automatically installed tools, see the `lint` workflow
      # for the others.
      pre-test-hook: |
        # TODO: Reinstate this after 0.9.0
        # cargo run -- -v run --only-tool='cargo clippy' --only-tool='cargo fmt' --only-tool='shellcheck'
